---
RuhohSpec: '2.0.alpha'

production_url: http://www.mikesboatworks.com

asset_pipeline:
  enable: true

'theme-clean-canvas':
  use: 'theme'

# how to set default properties?
#   page:
#     position: 99
_root:
  layout: theme
  sort: ['position', 'asc']
